---
abstract: "RFC 2553's C<getaddrinfo> and C<getnameinfo>\nfunctions."
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  ExtUtils::CBuilder: 0
  ExtUtils::CChecker: 0.04
  Module::Build: 0
  Module::Build::Compat: 0
  Scalar::Util: 0
  Test::More: 0
configure_requires:
  ExtUtils::CBuilder: 0
  ExtUtils::CChecker: 0.04
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Socket-GetAddrInfo
provides:
  Socket::GetAddrInfo:
    file: lib/Socket/GetAddrInfo.pm
    version: 0.19_002
  Socket::GetAddrInfo::PP:
    file: lib/Socket/GetAddrInfo/PP.pm
    version: 0.19_002
requires:
  XSLoader: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.19_002
