---
name: Socket-GetAddrInfo
version: 0.13
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
abstract: |-
  RFC 2553's C<getaddrinfo> and C<getnameinfo>
  functions.
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  ExtUtils::CBuilder: 0
  Module::Build: 0
  Module::Build::Compat: 0
  Scalar::Util: 0
  Test::Exception: 0
  Test::More: 0
  Test::Warn: 0
configure_requires:
  ExtUtils::CBuilder: 0
  Module::Build: 0.35
provides:
  Socket::GetAddrInfo:
    file: lib/Socket/GetAddrInfo.pm
    version: 0.13
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
